import { RadioButtonChecked } from "@mui/icons-material";
import { List, ListItem, ListItemIcon, ListItemText } from "@mui/material";
import { NextPage } from "next";
import Image from "next/legacy/image";
import Link from "next/link";
import React from "react";
import PolicyDropdown from "../../../components/policies/PolicyDropdown";
import { NextSeo } from "next-seo";

const Index = () => {
  return (
    <>
      <NextSeo title={"AI Policy"} />
      <h1 className="mx-auto my-40 text-center text-6xl text-gray-200 ">
        AI Policy
      </h1>
      <div className=" mx-10 flex w-[100vw-5rem] flex-col items-center  justify-center pl-10 text-center align-middle ">
        <p className="my-2 -ml-5 text-xl font-bold text-gray-200">
          Last updated: May 16, 2023
        </p>
        <p className="h-auto text-2xl">
          This AI policy describes the extend to which we use artificial
          tehnologies to deliver our products
        </p>
        <PolicyDropdown
          title="How do we utilize AI?"
          content={
            <>
              Aftin utilizes AI tehnologies primarily to generate images that we
              give access to. We do not assume copyright ownership of any image
              fully generated by an artificial intelligence, nor do we charge
              for copyright access to any image. Rather our subscriptions charge
              clients for the access to a large databas of images and other
              services. Not every image that we give access to will be
              fullygenerated by an AI model<br></br>
              <span className="my-2 text-2xl font-bold">
                These are the types of data we collect :
              </span>
              <br></br>
              We also utilize AI tehnologies to :
              <List sx={{ width: "100%" }}>
                <ListItem>
                  <ListItemIcon>
                    <RadioButtonChecked color="info" />
                  </ListItemIcon>
                  <ListItemText primary="Create images or patterns used directly or indirectly in designing our website or other marketing material" />
                </ListItem>
                <ListItem>
                  <ListItemIcon>
                    <RadioButtonChecked color="info" />
                  </ListItemIcon>
                  <ListItemText primary="Give access to AI models that enhance images for our clients" />
                </ListItem>
                <ListItem>
                  <ListItemIcon>
                    <RadioButtonChecked color="info" />
                  </ListItemIcon>
                  <ListItemText primary="Enhance images for our own usage" />
                </ListItem>
              </List>
            </>
          }
        />

        <PolicyDropdown
          title="What AI tehnologies do we utilize"
          content={
            <>
              <span className="my-2 text-2xl font-bold">
                This is a list containing all of the AI's used (including how
                they are / were used) in the past or currently by Aftin :
              </span>
              <br></br>
              <span className="my-2 text-2xl font-bold text-red-400 ">
                We do NOT claim ownership over any of these AI models
              </span>
              <br></br>
              <List sx={{ width: "100%" }}>
                <ListItem>
                  <ListItemIcon>
                    <RadioButtonChecked color="info" />
                  </ListItemIcon>
                  <ListItemText primary="Midjourney by Midjourney inc. Used in generating images in our database offered to our clients and also in generating icons and images used on our website or other marketing material" />
                </ListItem>
                <ListItem>
                  <ListItemIcon>
                    <RadioButtonChecked color="info" />
                  </ListItemIcon>
                  <ListItemText primary="Stable Diffusion by Stablility AI. See Midjourney usage" />
                </ListItem>
                <ListItem>
                  <ListItemIcon>
                    <RadioButtonChecked color="info" />
                  </ListItemIcon>
                  <ListItemText primary="Clipstyler by Gihyun Kwon, Jong Chul Ye. Used in order to give our clients access to features that let you stylize and deblur images" />
                </ListItem>
                <ListItem>
                  <ListItemIcon>
                    <RadioButtonChecked color="info" />
                  </ListItemIcon>
                  <ListItemText primary="Swinir by Jingyun Liang et al. . Used in order to give our clients access to upscale image abilities." />
                </ListItem>
              </List>
            </>
          }
        />
      </div>
    </>
  );
};

export default Index;
