export {default as UploadMainDishes} from './UploadMainDishes'
export {default as UploadSweetsAndDesserts} from './UploadSweetsAndDesserts'
export {default as UploadFastFoods} from './UploadFastFoods'
export {default as UploadDrinks} from './UploadDrinks'
export {default as UploadFlyers} from './UploadFlyers'
export {default as UploadIngredients} from './UploadIngredients'
export {default as UploadLogos} from './UploadLogos'
export {default as UploadMenus} from './UploadMenus'
export {default as UploadArtworks} from './UploadArtworks'
export {default as UploadStickersAndCliparts} from './UploadStickersAndCliparts'
export {default as UploadBrochures} from './UploadBrochures'
export {default as UploadOther} from './UploadOther'
export {default as UploadUtensilsAndPlates} from './UploadOther'


