import { RadioButtonChecked } from '@mui/icons-material'
import { List, ListItem, ListItemIcon, ListItemText } from '@mui/material'
import { NextPage } from 'next'
import Image from "next/legacy/image"
import Link from 'next/link'
import React from 'react'
import PolicyDropdown from '../../../components/policies/PolicyDropdown'


const Index = () => {

  return (
    <div className='font-lg'>
      <h1 className='mx-auto my-40 text-6xl text-center text-gray-200 '>Privacy Policy</h1>
      <div className=' w-[100vw-5rem] mx-10 pl-10 flex flex-col  text-center align-middle justify-center items-center '>
        <p className='text-xl my-2 font-bold text-gray-200 -ml-5'>Last updated: January 14, 2023</p>
        <p className='text-2xl h-auto'>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You
        </p>
        <PolicyDropdown title='Interpretation and Definitions' content={
          <>
            <span className='font-bold ml-2'>Interpretation:</span><br></br>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.  <br></br>
            <span className='font-bold ml-2'>Definitions:</span> <br></br>
            For the purposes of this Privacy Policy: <br></br>
            Account means a unique account created for You to access our Service or parts of our Service.
            Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to <span className='text-red-500 text-2xl'>TO BE FILLLED IN</span> <br></br>
            Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.<br></br>
            Country refers to: Romania<br></br>
            Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.<br></br>
            Personal Data is any information that relates to an identified or identifiable individual.<br></br>
            Service refers to the Website.<br></br>
            Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.<br></br>
            Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).<br></br>
            Website refers to Aftin, accessible from https://www.aftin.net<br></br>
            You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.<br></br>
          </>
        } />

        <PolicyDropdown title='What data we collect' content={
          <>
            <span className='text-2xl my-2 font-bold'>These are the types of data we collect :</span><br></br>
            <span className='font-bold ml-2' >Personal Data</span><br></br>
            <span>
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: <br></br>
              <List
                sx={{ width: '100%' }}
              >
                <ListItem>
                  <ListItemIcon>
                    <RadioButtonChecked color='info' />
                  </ListItemIcon>
                  <ListItemText primary='Email' />
                </ListItem>
                <ListItem>
                  <ListItemIcon>
                    <RadioButtonChecked color='info' />
                  </ListItemIcon>
                  <ListItemText primary='First and last name (if you provide it)' />
                </ListItem>
                <ListItem>
                  <ListItemIcon>
                    <RadioButtonChecked color='info' />
                  </ListItemIcon>
                  <ListItemText primary='Usage Data' />
                </ListItem>
              </List>
              Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
              We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
              All of these are collected only if you consent to our cookie policy or by you directly sending this data to us through activities such as registering to our website or others.
            </span>
          </>
        } />

        <PolicyDropdown title='How do we collect this data' content={
          <>
            <span>
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
              <List
                sx={{ width: '100%' }}
              >
                <ListItem>
                  <ListItemIcon>
                    <RadioButtonChecked color='info' />
                  </ListItemIcon>
                  <ListItemText primary={
                    <>
                      <span className='font-bold'>Cookies or Browser Cookies: </span><span>A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies</span>
                    </>
                  } />
                </ListItem>
                <ListItem>
                  <ListItemIcon>
                    <RadioButtonChecked color='info' />
                  </ListItemIcon>
                  <ListItemText primary={
                    <>
                      <span className='font-bold'>Web Beacons: </span><span>A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies</span>
                    </>
                  } />
                </ListItem>
              </List>
              Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
              We use both Session and Persistent Cookies for the purposes set out below: <br></br>
              <span className=''>
                <span className='font-bold  ml-2 text-red-300'>Essential / Functionality Cookies </span> <br></br>
                <span className='font-bold  ml-2'>Type: Session & Persistent Cookies</span><br></br>
                <span className='font-bold  ml-2'>Administered by: Us</span><br></br>
                Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and keep the logged in when they revisit the Website, save your cookie consent choice, save a link of an image that you were browsing before you were taken to another page of the Website and so forth. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.<br></br>
                <span className='font-bold  ml-2 text-red-300'>Analytic Cookies </span> <br></br>
                <span className='font-bold  ml-2'>Type: Persistent Cookies</span><br></br>
                <span className='font-bold  ml-2'>Administered by: Google</span><br></br>
                Google Analytics uses several different cookies to track users and their behavior on the Website, to distinguish and remember them over time and upon repeated visits. These cookies track your activity on our website and we use them to improve our product by analyzing our traffic
                Data that Analytics Cookies collect includes but are is not limited to :
                <List
                  sx={{ width: '100%' }}
                >
                  <ListItem>
                    <ListItemIcon>
                      <RadioButtonChecked color='info' />
                    </ListItemIcon>
                    <ListItemText primary={`ClientIDs consisting of a string of numbers unique to each user on your website`} />
                  </ListItem>
                  <ListItem>
                    <ListItemIcon>
                      <RadioButtonChecked color='info' />
                    </ListItemIcon>
                    <ListItemText primary={`Number of times and time of day of previous visits to your website`} />
                  </ListItem>
                  <ListItem>
                    <ListItemIcon>
                      <RadioButtonChecked color='info' />
                    </ListItemIcon>
                    <ListItemText primary={`Information about how they found your website, their search and browser history`} />
                  </ListItem>
                  <ListItem>
                    <ListItemIcon>
                      <RadioButtonChecked color='info' />
                    </ListItemIcon>
                    <ListItemText primary={`IP addresses`} />
                  </ListItem>
                </List>
                They do not personally identify You as an individual visitor to Google <br></br>
                <span className='font-bold  ml-2 text-red-300'>Advertising Cookies </span> <br></br>
                <span className='font-bold  ml-2'>Type: Persistent Cookies</span><br></br>
                <span className='font-bold  ml-2'>Administered by: Google</span><br></br>
                Google and other Third Party Vendors use cookies to serve ads based on a user's prior visits to the Website or other websites. They allow Google and its partners to serve you ads based on your visits on the Website and/or other sites on the internet. <br></br>
                Data that Advertising Cookies collect includes but are is not limited to :
                <List
                  sx={{ width: '100%' }}
                >
                  <ListItem>
                    <ListItemIcon>
                      <RadioButtonChecked color='info' />
                    </ListItemIcon>
                    <ListItemText primary={`Demographic information such as age, gender, location, and language.`} />
                  </ListItem>
                  <ListItem>
                    <ListItemIcon>
                      <RadioButtonChecked color='info' />
                    </ListItemIcon>
                    <ListItemText primary={`Behavior information such as session length, pages visited in a session, and bounce rate.`} />
                  </ListItem>
                  <ListItem>
                    <ListItemIcon>
                      <RadioButtonChecked color='info' />
                    </ListItemIcon>
                    <ListItemText primary={`User conversion information.`} />
                  </ListItem>
                  <ListItem>
                    <ListItemIcon>
                      <RadioButtonChecked color='info' />
                    </ListItemIcon>
                    <ListItemText primary={`Browser and device information, such as what device You are on, the exact OS, and mobile screen size.`} />
                  </ListItem>
                </List>
                <span className='font-bold  ml-2 text-red-300'>Security Cookies </span> <br></br>
                <span className='font-bold  ml-2'>Type: Persistent Cookies</span><br></br>
                <span className='font-bold  ml-2'>Administered by: Google</span><br></br>
                These Cookies are related to security such as authentication storage, fraud prevention and other user protection. They ensure that only the actual owner of the account can access that account. Some cookies and other technologies are used to prevent spam, fraud, and abuse.

              </span>

            </span>
          </>
        } />

        <PolicyDropdown title='What do we use this data for' content={
          <>
            <span className='text-red-300 font-bold'>The Company may use Personal Data for the following purposes:</span> <br></br>
            <List
              sx={{ width: '100%' }}
            >
              <ListItem>
                <ListItemIcon>
                  <RadioButtonChecked color='info' />
                </ListItemIcon>
                <ListItemText primary={` To provide and maintain our Service, including to monitor the usage of our Service.`} />
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <RadioButtonChecked color='info' />
                </ListItemIcon>
                <ListItemText primary={`To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.`
                } />
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <RadioButtonChecked color='info' />
                </ListItemIcon>
                <ListItemText primary={` For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.`
                } />
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <RadioButtonChecked color='info' />
                </ListItemIcon>
                <ListItemText primary={` To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.`
                } />
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <RadioButtonChecked color='info' />
                </ListItemIcon>
                <ListItemText primary={` To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
            To manage Your requests: To attend and manage Your requests to Us.`
                } />
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <RadioButtonChecked color='info' />
                </ListItemIcon>
                <ListItemText primary={`For analytics purposes : By tracking your activity on the website we can discover the pages / products that are popular or not popular, thus allowing us to improve our product offers to fit our customer's desires. We also identify trends, evaluate and improve our newly added or existing features alongside promotional campaigns and so forth `}
                />
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <RadioButtonChecked color='info' />
                </ListItemIcon>
                <ListItemText primary={`For advertising purposes : Through our partners we use your data to display you personalized ads. `}
                />
              </ListItem>
              <span>
                We may share Your personal information in the following situations: <br></br>
                •	With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You. <br></br>
                •	For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.
                •	With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us. <br></br>
                •	With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.
                •	With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. <br></br>
                •	With Your consent: We may disclose Your personal information for any other purpose with Your consent. <br></br>

              </span>

            </List>

          </>
        } />
        <PolicyDropdown title='How do we save and protect your data' content={
          <>
            <span>
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
            </span><br></br>

            The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods. <br></br>
            <span className='font-bold'>Transfer of Your Personal Data</span><br></br>
            Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
            Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.<br></br>
            <span className='font-bold'>Delete Your Personal Data</span><br></br>
            You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
            Our Service may give You the ability to delete certain information about You from within the Service.
            You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.<br></br>
            Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.<br></br>
            <span className='font-bold text-red-300'>Disclosure of Your Personal Data : </span><br></br>
            <span className='font-bold '>Business Transactions </span><br></br>
            If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
            Law enforcement<br></br>
            Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).<br></br>
            Other legal requirements<br></br>
            The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:<br></br>
            •	Comply with a legal obligation<br></br>
            •	Protect and defend the rights or property of the Company<br></br>
            •	Prevent or investigate possible wrongdoing in connection with the Service<br></br>
            •	Protect the personal safety of Users of the Service or the public<br></br>
            •	Protect against legal liability<br></br>
            Security of Your Personal Data<br></br>
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.<br></br>
          </>
        } />

        <PolicyDropdown title='Changes to this Privacy Policy' content={
          <>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. <br></br>
            We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.<br></br>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page. <br></br>
          </>
        } />
      </div>
      <div className='mx-auto text-center'>
        If you have any questions about this Privacy Policy, You can contact us: <br></br>
        <span className='text-4xl text-red-500'> TO BE FILLED IN</span><br></br>
        •	By email: aftinsg@gmail.com<br></br>
      </div>


    </div>
  )
}

export default Index